--Selection de la base

USE S1B_leflochic_merciertallet

--Vidage des tables 
DELETE VIN_ACHETÉ
DELETE CLASSEMENT1855 
DELETE Vin
DELETE Commande
DELETE CHATEAU




--Création des chateaux
INSERT INTO CHATEAU(NOMCHATEAU,ADRESSE,COORDONNEESBANCAIRE,NOMCONTACT,NUMTELCONTACT,APPELLATIONVITICOLE)
VALUES ('Chateau LAFITE-ROTHSCHILD','17 Rue de la Rolland','1','Silvie','07574349','Pauillac'),
('Chateau LATOUR','4 CHEM du Calvaire','1','Florence','07868801','Pauillac'),
('Chateau Pontet-Canet ','33250 Pauillac','1','Martin','0786880110','Pauillac'),
('Chateau Saint-Pierre','33250 Pauillac','1','Tanguy','0698783709','Saint-Julien'),
('Chateau Kirwan','Chem. de Kirwan', '1','Marie','07003263','Margaux'),
('Chateau RAUZAN-SÉGLA','Rue Alexis Millardet','1','Florence','07868801','Pessac'),
('Chateau LÉOVILLE LAS CASES','Saint Julien Beychevelle','1','Clément','06361844','Saint-Julien'),
('Chateau LÉOVILLE-POYFERRÉ','Rue Saint-Julien','1','Veronique','07461295','Saint-Julien')


--Création des vins
INSERT INTO Vin(MILLÉSIME,QUANTITÉ,codeChateau)
VALUES('2014',15,(SELECT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LAFITE-ROTHSCHILD')),
('2015',7,(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('2015',3,(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau RAUZAN-SÉGLA')),
('2019',4,(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Pontet-Canet')),
('2020',1,(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LATOUR')) 


--Création des classements 
INSERT INTO Classement1855(codeVin,CRU,cote,prix)
VALUES((SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2020'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LATOUR')),'Premiers Crus','2020',768),
((SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2019'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Pontet-Canet')),'Deuxieme Crus','2019',560),
((SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2015'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau RAUZAN-SÉGLA')),'Troisieme cru','2015',695),
((SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2015'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),'Quatrieme cru','2015',875),
((SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2014' AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LAFITE-ROTHSCHILD')),'Cinquieme cru','2014',730)

--Création des commandes 
INSERT INTO Commande(DATEACHAT,dateLivraisonEstimée,adresseLivraison,codeChateau)
VALUES ('20/01/2022','24/01/2022','impasse de Parent,Cordierdan',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('11/12/2021','16/12/2021','Rue Rocher,Martynec',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('08/08/2021','15/08/2021','17 rue Regnier,Guillot',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('31/12/2021','10/01/2022','Impasse Raymond Gillet,Brun',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('31/07/2021','04/08/2021','Rue Gilles Legendre,MenardBourg',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),
('10/01/2021','22/01/2021','Rue de Barbe,Bazin',(SELECT codeChateau FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre'))

--Création des vins achetés 
INSERT INTO VIN_ACHETÉ(PRIX,QUANTITÉ,CODEVIN,NDECOMMANDE)
VALUES 
(100,10,(SELECT  CODEVIN FROM VIN WHERE MILLÉSIME='2019'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Pontet-Canet')),(SELECT NDECOMMANDE FROM COMMANDE WHERE ADRESSELIVRAISON='impasse de Parent,Cordierdan')),
(2000,20,(SELECT CODEVIN FROM VIN WHERE MILLÉSIME='2015'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau Saint-Pierre')),(SELECT NDECOMMANDE FROM COMMANDE WHERE ADRESSELIVRAISON='17 rue Regnier,Guillot')),
(1000,2,(SELECT CODEVIN FROM VIN WHERE MILLÉSIME='2020'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LATOUR')),(SELECT NDECOMMANDE FROM COMMANDE WHERE ADRESSELIVRAISON='Impasse Raymond Gillet,Brun')),
(500,6,(SELECT CODEVIN FROM VIN WHERE MILLÉSIME='2014'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau LAFITE-ROTHSCHILD')),(SELECT NDECOMMANDE FROM COMMANDE WHERE ADRESSELIVRAISON='Rue Gilles Legendre,MenardBourg')),
(150,3,(SELECT CODEVIN FROM VIN WHERE MILLÉSIME='2015'AND CODECHATEAU=(SELECT DISTINCT CODECHATEAU FROM CHATEAU WHERE NOMCHATEAU='Chateau RAUZAN-SÉGLA')),(SELECT NDECOMMANDE FROM COMMANDE WHERE ADRESSELIVRAISON='Rue de Barbe,Bazin'))






