USE S1B_leflochic_merciertallet
/*~~~COMMANDE~~~*/

/*Création d’une nouvelle commande*/
INSERT INTO COMMANDE VALUES ('....')

/*Lister les commandes*/
SELECT *
FROM COMMANDE

/*Lister les vins achetés lors d’une commande*/
SELECT MILLÉSIME,NOMCHATEAU
FROM VIN_ACHETÉ
INNER JOIN VIN ON VIN_ACHETÉ.CODEVIN = VIN.CODEVIN
INNER JOIN COMMANDE ON COMMANDE.NDECOMMANDE = VIN_ACHETÉ.NDECOMMANDE
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
WHERE COMMANDE.NDECOMMANDE='...'

/*Lister les vins par prix*/
SELECT MILLÉSIME,NOMCHATEAU
FROM VIN_ACHETÉ
INNER JOIN VIN ON VIN_ACHETÉ.CODEVIN = VIN.CODEVIN
INNER JOIN COMMANDE ON COMMANDE.NDECOMMANDE = VIN_ACHETÉ.NDECOMMANDE
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
WHERE COMMANDE.NDECOMMANDE='...'
ORDER BY PRIX ASC

/*Connaître la date estimée pour une commande*/
SELECT DATELIVRAISONESTIMÉE
FROM COMMANDE

/*Connaître la date où une commande a été effectuée*/
SELECT DATEACHAT
FROM COMMANDE

/*Modifier la quantité achetée*/
UPDATE VIN_ACHETÉ 
SET QUANTITÉ='' 
WHERE CODEVIN='...'

/*Supprimer une commande*/
DELETE FROM COMMANDE
WHERE NDECOMMANDE='...'


/*~~~VIN~~~*/

/*Ajouter un vin à la liste*/
INSERT INTO VIN VALUES ('....')

/*Connaître le millésime d’un vin*/
SELECT MILLÉSIME
FROM VIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU=VIN.CODECHATEAU
WHERE NOMCHATEAU='...'

/*Connaître la quantité d’un vin que possède Grave et Cie*/
SELECT QUANTITÉ, NOMCHATEAU, MILLÉSIME
FROM VIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
WHERE NOMCHATEAU='...' AND MILLÉSIME='...'

/*Lister les vins par quantité*/
SELECT QUANTITÉ, NOMCHATEAU, MILLÉSIME
FROM VIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
ORDER BY QUANTITÉ ASC

/*Savoir si un vin fait partie du classement de 1855*/
SELECT MILLÉSIME, NOMCHATEAU
FROM VIN
INNER JOIN CLASSEMENT1855 ON CLASSEMENT1855.CODEVIN=VIN.CODEVIN 
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU=VIN.CODECHATEAU 
WHERE CRU IS NOT NULL

/*Modifier la quantité stockée d’un vin*/
UPDATE VIN 
SET QUANTITÉ='....'
WHERE MILLÉSIME='...' AND (SELECT NOMCHATEAU FROM CHATEAU)='...'

/*Supprimer un vin*/
DELETE FROM VIN
WHERE MILLÉSIME='...' AND (SELECT NOMCHATEAU FROM CHATEAU)='...'


/*~~~CHATEAU~~~*/

/*Ajouter un château */
INSERT INTO CHATEAU VALUES ('....')

/*Lister les châteaux */
SELECT NOMCHATEAU
FROM CHATEAU

/*Connaître un contact du château, et comment le contacter*/
SELECT NOMCONTACT,NUMTELCONTACT
FROM CHATEAU
WHERE NOMCHATEAU='...'

/*Connaître les coordonnées bancaire d’un château*/
SELECT COORDONNEESBANCAIRE
FROM CHATEAU
WHERE NOMCHATEAU='...'

/*Pour un château, connaître le nombre de vins venant de ce dernier*/
SELECT QUANTITÉ
FROM CHATEAU
INNER JOIN VIN  ON VIN.CODECHATEAU = CHATEAU.CODECHATEAU
WHERE NOMCHATEAU='...'

/*Modification des différents attributs : le contact, son numéro de téléphone, les coordonnées bancaires d’un château*/
UPDATE CHATEAU 
SET NUMTELCONTACT='....',NOMCONTACT='...', COORDONNEESBANCAIRE='...'
WHERE NOMCHATEAU='...'

/*Retirer un château*/
DELETE FROM CHATEAU
WHERE NOMCHATEAU='...'


/*~~~VIN_ACHETÉ~~~*/

/*Connaître le prix associé à un vin lors d’une commande  */
SELECT PRIX,NOMCHATEAU,MILLÉSIME
FROM VIN_ACHETÉ
INNER JOIN VIN ON VIN.CODEVIN=VIN_ACHETÉ.CODEVIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU=VIN.CODECHATEAU
WHERE NOMCHATEAU='...' AND MILLÉSIME='...'

/*Connaître la quantité associée à un vin lors d’une commande*/
SELECT VIN_ACHETÉ.QUANTITÉ,NOMCHATEAU,MILLÉSIME
FROM VIN_ACHETÉ
INNER JOIN VIN ON VIN.CODEVIN=VIN_ACHETÉ.CODEVIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU=VIN.CODECHATEAU
WHERE NOMCHATEAU='...' AND MILLÉSIME='...'

/*Modifier le prix */
UPDATE VIN_ACHETÉ 
SET QUANTITÉ='....'
WHERE CODEVIN='...' 
	
/*Modifier la quantité*/	
UPDATE VIN_ACHETÉ 
SET PRIX='....'
WHERE CODEVIN='...'

/*Supprimer un enregistrement si la commande est annulée*/
DELETE FROM VIN_ACHETÉ
WHERE CODEVIN='...' and NDECOMMANDE='...'


/*~~~CLASSEMENT 1855~~~*/

/*Connaître les vins faisant partis du classement 1855  */
SELECT MILLÉSIME,NOMCHATEAU
FROM CLASSEMENT1855
INNER JOIN VIN ON VIN.CODEVIN = CLASSEMENT1855.CODEVIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
WHERE NCLASSEMENT IS NOT NULL

/*Connaître la cote, le numéro de cru et le prix d’un vin */
SELECT COTE,CRU,PRIX
FROM CLASSEMENT1855
INNER JOIN VIN ON VIN.CODEVIN = CLASSEMENT1855.CODEVIN
INNER JOIN CHATEAU ON CHATEAU.CODECHATEAU = VIN.CODECHATEAU
WHERE NOMCHATEAU='...' AND MILLÉSIME='...'

/*Modifier le prix d’un vin du classement */
UPDATE CLASSEMENT1855
SET PRIX='....'
WHERE NCLASSEMENT='...'